### ISSUE TITLE
wrong configcenter settings in *.properties

### ISSUE THREAD

**Issue by zhaixiaoxiang** [apache/incubator-dubbo-samples#72]
In many configcenter related samples, such as module `dubbo-samples-metadata-report-configcenter`,  we could see `dubbo.configCenter.address=xxxxxx` settings, but this is wrong, correct key is `dubbo.config-center.address` 

When we start MetadataConfigcenterProvider.main(), there are failures as following:
```
Exception in thread "main" java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry zookeeperProtocol="false" valid="false" prefix="dubbo.registry" />
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:162)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:270)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:328)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:318)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:112)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.apache.dubbo.samples.metadatareport.configcenter.MetadataConfigcenterProvider.main(MetadataConfigcenterProvider.java:45)

```

![image](https://user-images.githubusercontent.com/11908486/56737386-e8cfc380-679c-11e9-967a-9c27f440590b.png)

**Comment by DeppWang** [comment]
I pulled the latest code, but when I start `dubbo-samples-configcenter` project, still exist this error:
```
Exception in thread "main" java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry valid="false" zookeeperProtocol="false" prefix="dubbo.registry" />
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:162)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:270)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:328)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:318)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:112)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.apache.dubbo.samples.configcenter.annotation.AnnotationProvider.main(AnnotationProvider.java:37)
```
#74 was fix the wrong configcenter settings in *.properties. Do I still need change some local code or configuration before I first start project?

**Comment by zhaixiaoxiang** [comment]
@DeppWang 

Project dubbo-samples-configcenter-annotation ? It runs ok in my machine. Could you give me the reproductive samples?

**Comment by DeppWang** [comment]
> @DeppWang
> 
> Project dubbo-samples-configcenter-annotation ? It runs ok in my machine. Could you give me the reproductive samples?

I'm not change the any code, It's latest.

**Comment by DeppWang** [comment]
@zhaixiaoxiang The `dubbo-samples-configcenter` all sub-modules run error, It's all this fault!
